services:
  trino:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: trino-plugin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/data:/var/trino/data
      - ./docker/etc/catalog:/etc/trino/catalog
      - ./docker/csv:/data/csv
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: trino-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio/data:/data
    restart: unless-stopped
