services:
  trino:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: trino-plugin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/data/trino:/var/trino/data
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: trino-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/data/minio:/data
    restart: unless-stopped

  tests:
    image: maven:3.9.11-eclipse-temurin-25
    working_dir: /workspace
    volumes:
      - .:/workspace
      - maven-repo:/root/.m2
    command: mvn test

volumes:
  maven-repo:
