services:
  trino-coordinator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: trino-s3file:latest
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./docker/etc/config.properties:/etc/trino/config.properties:ro
      - ./docker/etc/node.properties:/etc/trino/node.properties:ro
    depends_on:
      - minio
    restart: unless-stopped

  trino-worker-1:
    image: trino-s3file:latest
    container_name: trino-worker-1
    volumes:
      - ./docker/etc/worker:/etc/trino-worker:ro
    entrypoint: ["/etc/trino-worker/entrypoint.sh"]
    environment:
      TRINO_NODE_ID: trino-worker-1
    depends_on:
      - minio
      - trino-coordinator
    restart: unless-stopped

  trino-worker-2:
    image: trino-s3file:latest
    container_name: trino-worker-2
    volumes:
      - ./docker/etc/worker:/etc/trino-worker:ro
    entrypoint: ["/etc/trino-worker/entrypoint.sh"]
    environment:
      TRINO_NODE_ID: trino-worker-2
    depends_on:
      - minio
      - trino-coordinator
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: trino-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  tests:
    image: maven:3.9.11-eclipse-temurin-25
    working_dir: /workspace
    volumes:
      - .:/workspace
      - maven-repo:/root/.m2
    command: mvn test
    profiles:
      - tests

volumes:
  maven-repo:
  minio-data:
